code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dcasella.i3
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension GrapeCity.gc-excelviewer
code --install-extension kriegalex.vscode-cudacpp
code --install-extension mechatroner.rainbow-csv
code --install-extension mitaki28.vscode-clang
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode.cpptools
code --install-extension naumovs.color-highlight
code --install-extension ocamllabs.ocaml-platform
code --install-extension rebornix.ruby
code --install-extension redhat.java
code --install-extension tomoki1207.pdf
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension wesbos.theme-cobalt2
code --install-extension wingrunr21.vscode-ruby
